### PR TITLE
Disable lzo2 for bsdtar

### LINKED ISSUE #72: Error building bsdtar for OS X substrate
When trying to build the OS X substrate, I get this error building bsd tar:

```
...
Notice: /Stage[main]/Ruby::Source/File[/vagrant-substrate/staging/embedded/include/ruby-2.2.0/x86_64-darwin15]/ensure: created
Notice: /Stage[main]/Ruby::Source/Exec[remove-ruby-rpaths]: Triggered 'refresh' from 1 events
Notice: /Stage[main]/Bsdtar::Posix/Autotools[libarchive]/Exec[make-libarchive]/returns: /Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
Notice: /Stage[main]/Bsdtar::Posix/Autotools[libarchive]/Exec[make-libarchive]/returns:   CCLD     libarchive.la
Notice: /Stage[main]/Bsdtar::Posix/Autotools[libarchive]/Exec[make-libarchive]/returns: clang: warning: argument unused during compilation: '-pthread'
Notice: /Stage[main]/Bsdtar::Posix/Autotools[libarchive]/Exec[make-libarchive]/returns: Undefined symbols for architecture i386:
Notice: /Stage[main]/Bsdtar::Posix/Autotools[libarchive]/Exec[make-libarchive]/returns:   "___lzo_init_v2", referenced from:
Notice: /Stage[main]/Bsdtar::Posix/Autotools[libarchive]/Exec[make-libarchive]/returns:       _archive_write_add_filter_lzop in archive_write_add_filter_lzop.o
Notice: /Stage[main]/Bsdtar::Posix/Autotools[libarchive]/Exec[make-libarchive]/returns:   "_lzo1x_1_15_compress", referenced from:
Notice: /Stage[main]/Bsdtar::Posix/Autotools[libarchive]/Exec[make-libarchive]/returns:       _drive_compressor in archive_write_add_filter_lzop.o
Notice: /Stage[main]/Bsdtar::Posix/Autotools[libarchive]/Exec[make-libarchive]/returns:   "_lzo1x_1_compress", referenced from:
Notice: /Stage[main]/Bsdtar::Posix/Autotools[libarchive]/Exec[make-libarchive]/returns:       _drive_compressor in archive_write_add_filter_lzop.o
Notice: /Stage[main]/Bsdtar::Posix/Autotools[libarchive]/Exec[make-libarchive]/returns:   "_lzo1x_999_compress_level", referenced from:
Notice: /Stage[main]/Bsdtar::Posix/Autotools[libarchive]/Exec[make-libarchive]/returns:       _drive_compressor in archive_write_add_filter_lzop.o
Notice: /Stage[main]/Bsdtar::Posix/Autotools[libarchive]/Exec[make-libarchive]/returns:   "_lzo1x_decompress_safe", referenced from:
Notice: /Stage[main]/Bsdtar::Posix/Autotools[libarchive]/Exec[make-libarchive]/returns:       _lzop_filter_read in archive_read_support_filter_lzop.o
Notice: /Stage[main]/Bsdtar::Posix/Autotools[libarchive]/Exec[make-libarchive]/returns:   "_lzo_adler32", referenced from:
Notice: /Stage[main]/Bsdtar::Posix/Autotools[libarchive]/Exec[make-libarchive]/returns:       _drive_compressor in archive_write_add_filter_lzop.o
Notice: /Stage[main]/Bsdtar::Posix/Autotools[libarchive]/Exec[make-libarchive]/returns:       _make_header in archive_write_add_filter_lzop.o
Notice: /Stage[main]/Bsdtar::Posix/Autotools[libarchive]/Exec[make-libarchive]/returns:   "_lzo_version", referenced from:
Notice: /Stage[main]/Bsdtar::Posix/Autotools[libarchive]/Exec[make-libarchive]/returns:       _archive_write_add_filter_lzop in archive_write_add_filter_lzop.o
Notice: /Stage[main]/Bsdtar::Posix/Autotools[libarchive]/Exec[make-libarchive]/returns:       _make_header in archive_write_add_filter_lzop.o
Notice: /Stage[main]/Bsdtar::Posix/Autotools[libarchive]/Exec[make-libarchive]/returns:   "_lzo_version_string", referenced from:
Notice: /Stage[main]/Bsdtar::Posix/Autotools[libarchive]/Exec[make-libarchive]/returns:       _archive_write_add_filter_lzop in archive_write_add_filter_lzop.o
Notice: /Stage[main]/Bsdtar::Posix/Autotools[libarchive]/Exec[make-libarchive]/returns: ld: symbol(s) not found for architecture i386
Notice: /Stage[main]/Bsdtar::Posix/Autotools[libarchive]/Exec[make-libarchive]/returns: clang: error: linker command failed with exit code 1 (use -v to see invocation)
Notice: /Stage[main]/Bsdtar::Posix/Autotools[libarchive]/Exec[make-libarchive]/returns: make[1]: *** [libarchive.la] Error 1
Notice: /Stage[main]/Bsdtar::Posix/Autotools[libarchive]/Exec[make-libarchive]/returns: make: *** [all] Error 2
```

When I downloaded the libarchive source tarball and built it by hand (no extra options to `./configure`), it built fine.

Any thoughts?

More info on my environment:

```
$ puppet --version
3.8.2
$ brew --version
0.9.5 (git revision d7e53; last commit 2015-12-03)
$ facter --version
2.4.4
$ brew cask list
facter  puppet
```

I tried to `brew cask install hiera` (v. 1.3.4), but it claimed to fail, yet it no longer prevented puppet from running.  Not good, but also not sure what that'd have to do with a bsdtar link error.

### PR DESCRIPTION
**Pull request by dbishop**
Not sure if this actually hurts anything, but I couldn't get bsdtar to
build on OS X 10.11.1 without disabling lzo2.

Fixes #72

### CODE REVIEW

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previous update so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
